name: ASP.NET Core CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test EasyUniAPI.Test/EasyUniAPI.Test.csproj --configuration Release --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish application
        run: dotnet publish EasyUniAPI.Web/EasyUniAPI.Web.csproj --configuration Release --output ./publish

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish
